// Shared question data parsed from Questions.csv
// This file is automatically generated - do not edit manually
// Generated: 2025-07-22T10:23:27.688Z

const QUESTION_DATA = {
  "Kinnari-Saraiya": [
    "When you entered a location, what did you expect to see? What appeared instead, and what was left out?",
    "Was the map a record, a performance, or a prediction?",
  ],

  "dmstfctn": [
    "example question 1",
    "example question 2",
  ],

  "Georgia-Gardner": [
    "example question 1",
    "example question 2",
  ],

  "Exhibition-Questions": [
    "What does “authenticity” in digital media mean to you?",
    "What does authenticity mean to you now, after experiencing this exhibition?",
    "What did you find most engaging, surprising, or thought-provoking during your visit?",
    "Were there any aspects of the exhibition that you found difficult to understand or access?",
    "What kinds of cues or signs do you usually look for to determine whether digital content (e.g., images, videos, texts) is authentic or not?",
    "Does any work in the exhibition challenge your assumptions about what is real or trustworthy?",
    "How did the exhibition make you feel, emotionally, intellectually, or otherwise?",
    "Were the themes and ideas of the exhibition clearly communicated to you? Why or why not?",
    "What responsibilities, if any, do artists have in helping the public engage with questions of authenticity in digital culture?",
    "Can you describe a moment in the exhibition that challenged or confirmed your understanding of authenticity?",
    "What one thing would you want the exhibition's artists to know after your visit?",
    "Did you feel included and considered in how the exhibition was designed and presented? If not, what could be improved?",
    "What responsibilities, if any, do technology companies have in helping the public engage with questions of authenticity in digital culture?",
    "How has the exhibition influenced your thoughts about the use of AI in creating or altering digital media?",
    "What aspects of the exhibition will you remember most vividly in six months?",
    "What responsibilities, if any, do researchers have in helping the public engage with questions of authenticity in digital culture?",
    "Do you think your behaviour might change when encountering digital content in the future (e.g., being more cautious, asking more questions, verifying information)? If so, in what way?",
    "Is there anything you would like to share about your personal experience with digital content that felt authentic—or inauthentic—and how it shaped your understanding of the digital world?",
    "How might the experience of this exhibition influence conversations you have with others about authenticity?",
  ],

};

// Export for use in other scripts
if (typeof window !== 'undefined') {
  window.QUESTION_DATA = QUESTION_DATA;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = QUESTION_DATA;
}